// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-_IiQ5-eYeu_BlYHJQ4p2M5KUs4wEEY',
    appId: '1:527793414557:web:e4f7cf97cbd0ed6e970f74',
    messagingSenderId: '527793414557',
    projectId: 'movie-app-db5e6',
    authDomain: 'movie-app-db5e6.firebaseapp.com',
    storageBucket: 'movie-app-db5e6.firebasestorage.app',
    measurementId: 'G-J43D61MQYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAok2kZYC8gNdyWwYXGUwLMqFfI8B4xkTc',
    appId: '1:527793414557:android:a334e15232f8df27970f74',
    messagingSenderId: '527793414557',
    projectId: 'movie-app-db5e6',
    storageBucket: 'movie-app-db5e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCRU33fdb04Aw6C8LpDbyFKuOq9hm5sw',
    appId: '1:527793414557:ios:220fdefe8c45f9eb970f74',
    messagingSenderId: '527793414557',
    projectId: 'movie-app-db5e6',
    storageBucket: 'movie-app-db5e6.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

}